[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"


[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"