[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.5"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "v0.3.0"

[[constraint]]
  name = "github.com/gorilla/feeds"
  version = "v1.1.0"